qlerner/models/word.py
from qlerner.main.database import db

class Word(db.Model):
    __tablename__ = 'words'
    
    id = db.Column(db.Integer, primary_key=True)
    english_meaning = db.Column(db.String(256), nullable=False)
    english_translation = db.Column(db.String(256), nullable=False)
    quenya_tengwar = db.Column(db.String(256), nullable=False)
    quenya_transcription = db.Column(db.String(256), nullable=False)

    def clone(self):
        d = dict(self.__dict__)
        d.pop("id")
        d.pop("_sa_instance_state")
        copy = self.__class__(**d)
        db.session.add(copy)
        db.session.commit()
        return copy

qlerner/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Email, Length

class LoginForm(FlaskForm):
    login_data = StringField('Email or Username', validators=[DataRequired(), 
        Length(max=120)])
    password = StringField('Password', validators=[DataRequired(), 
        Length(min=8, max=60)])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Log in')

qlerner/main/routes.py
from flask import Blueprint, request, flash, redirect, url_for, make_response, render_template, abort
from flask_login import login_user, current_user, logout_user, login_required
from flask_babel import gettext
from qlerner.models.user import *
from qlerner.models.exercise import *
from qlerner.models.lesson import *
from qlerner.models.word import *
from qlerner.models.tags import *
from qlerner.forms.login import LoginForm
from qlerner.forms.signin import SignupForm
from qlerner.main.database import db
from sqlalchemy import text
from random import sample
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash
from validate_email import validate_email

routes = Blueprint('routes', __name__)

def locale_select():
    return request.cookies.get('LANG', 'en')

@routes.route('/switch_language/<lang_code>')
def switch_language(lang_code):
    response = make_response(redirect(request.referrer))
    response.set_cookie('LANG', lang_code)
    return response

@routes.route('/')
def home():
    text = "This is in english and $<This will be tengwar$>!"
    return render_template('index.html', text=text)

@routes.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data
        confirm_password = form.confirm_password.data

        if password != confirm_password:
            flash(gettext('Passwords do not match'), 'danger')
            return redirect(url_for('routes.signup'))

        existing_user = User.query.filter_by(username=username).first()
        if existing_user:
            flash(gettext('Username already exists'), 'danger')
            return redirect(url_for('routes.signup'))

        existing_email = User.query.filter_by(email=email).first()
        if existing_email:
            flash(gettext('Email already exists'), 'danger')
            return redirect(url_for('routes.signup'))
        hashed_password = generate_password_hash(password)
        new_user = User(username=username, password=hashed_password, 
            email=email)
        db.session.add(new_user)
        db.session.commit()

        flash(gettext('Account created successfully!'), 'success')
        return redirect(url_for('routes.login'))
    else:
        for err_field in form.errors:
            flash(form.errors[err_field])

    return render_template('signup.html', form=form)
   

@routes.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('routes.home'))

    form = LoginForm()
    if form.validate_on_submit():
         # Check if input is a valid email address
        if validate_email(form.login_data.data):
            user = User.query.filter_by(email=form.login_data.data).first()
        else:
            user = User.query.filter_by(username=form.login_data.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_me.data)
            return redirect(url_for('routes.home'))
        else:
            flash(gettext('Invalid login data!'), 'danger')
    else:
        for err_field in form.errors:
            flash(form.errors[err_field])

    return render_template('login.html', form=form)

@routes.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('routes.login'))

@routes.route('/profile')
@login_required
def profile():
    user = current_user
    
    query = text("SELECT * FROM {table} WHERE user_id = '{user_id}'"
        .format(
        table=user_completed_lessons_NAMETAG, user_id=user.id
    )) #TODO this shit is one to one relation and will fall if two users complete the same lesson
    solved_lessons = len(db.engine.connect().execute(query).fetchall())
    return render_template('profile.html', user=user, 
        solved_lessons=solved_lessons)

@routes.route('/choose_lesson', methods=['GET'])
@login_required
def choose_lesson():
    lessons = Lesson.query.all()
    return render_template('choose_lesson.html', lessons=lessons)

def return_options(exercise) -> list:
    if exercise.type == "choose one":
        all_words = Word.query.all()
        # remove the correct answer from the list of words
        words_without_answer = [word.quenya_tengwar for word 
            in all_words if word.quenya_tengwar != exercise.answer]
        # randomly select three wrong options from the remaining words
        wrong_options = sample(words_without_answer, 3)
        # combine the correct answer and the wrong options
        # shuffle the list
        return sample([exercise.answer] + wrong_options, k=4)
    return []

@routes.route('/solve_lesson/<int:lesson_id>', methods=['GET', 'POST'])
@login_required
def solve_lesson(lesson_id):
    lesson = Lesson.query.get_or_404(lesson_id)
    exercise_ids = lesson.exercise_ids.split(',')
    current_index = int(request.args.get('current_index', 0))
    current_exercise_id = int(exercise_ids[current_index])
    current_exercise = Exercise.query.get(current_exercise_id)
    current_exercise.options = return_options(current_exercise)
    if request.method == 'POST':
        # Check if answer is correct
        user_answer = request.form['answer']
        # TODO: that lower() WILL cause problems in future
        if user_answer.strip().lower() == current_exercise.answer.lower():
            # Update completed exercises for user
            user_completed_exercise = UserCompletedExercise.query.filter_by(
                user_id=current_user.id, 
                exercise_id=current_exercise.id).first()
            if user_completed_exercise:
                user_completed_exercise.times_completed += 1
            else:
                user_completed_exercise = UserCompletedExercise(
                    user_id=current_user.id, 
                    exercise_id=current_exercise.id, 
                    times_completed = 1)
                db.session.add(user_completed_exercise)
            db.session.commit()

            # Move on to next exercise or complete lesson
            if current_index == len(exercise_ids) - 1:
                # Mark lesson as completed
                user_completed_lesson = UserCompletedLesson.query.filter_by(
                    user_id=current_user.id, 
                    lesson_id=lesson.id).first()
                if user_completed_lesson:
                    user_completed_lesson.times_completed += 1
                    # user_completed_lesson.completed_at = datetime.now()
                else:
                    user_completed_lesson = UserCompletedLesson(
                        user_id=current_user.id, 
                        lesson_id=lesson.id, times_completed = 1)
                    db.session.add(user_completed_lesson)
                db.session.commit()

                flash(gettext('Congratulations, you have completed the lesson!'),
                    'success')
                return redirect(url_for('routes.choose_lesson'))

            next_index = current_index + 1
            next_exercise_id = int(exercise_ids[next_index])
            next_exercise = Exercise.query.get(next_exercise_id)
            next_exercise.options = return_options(next_exercise)
            return render_template('solve_lesson.html', 
                lesson=lesson, exercise=next_exercise, 
                current_index=next_index)

        else:
            flash(gettext('Incorrect answer, please try again'), 'danger')
    
    return render_template('solve_lesson.html', lesson=lesson, 
        exercise=current_exercise, current_index=current_index)

@routes.route('/dictionary')
def dictionary():
    words = Word.query.all()
    return render_template('dictionary.html', words=words)

def admin_required(func):
    @wraps(func)
    def decorated_view(*args, **kwargs):
        if not current_user.is_authenticated or current_user.role != 'admin':
            flash(gettext('You need to be an admin to access this page'), 
                'warning')
            return redirect(url_for('routes.home'))
        return func(*args, **kwargs)
    return decorated_view

qlerner/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
</head>
<body>
    {% block scripts %}{% endblock %}
    <header>
        <nav>
            <ul>
                <li><a href="{{ url_for('routes.home') }}">{{ gettext('Home') }}</a></li>
                <li><a href="{{ url_for('routes.dictionary') }}">{{ gettext('Dictionary') }}</a></li>
                <li>
                    <a href="{{ url_for('routes.switch_language', lang_code='en') }}">{{ gettext('English') }}</a>
                    <a href="{{ url_for('routes.switch_language', lang_code='ru') }}">{{ gettext('Русский') }}</a>
                </li>
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('routes.profile') }}">{{ gettext('Profile') }}</a></li>
                    <li><a href="{{ url_for('routes.choose_lesson') }}">{{ gettext('Choose lesson') }}</a></li>
                    <li><a href="{{ url_for('routes.logout') }}">{{ gettext('Logout') }}</a></li> 
                    {% if current_user.role == "admin" %}
                    <h2>{{ gettext('Admin actions!') }}</h2>
                    {% for entity in [gettext('User'), gettext('Lesson'), gettext('Exercise'), gettext('Word')] %}
                    <li><a href="{{ url_for(entity.lower() + '_routes.' + entity.lower() + 's') }}">{{ gettext('Manage') }} {{ entity }}s</a>
                    <a href="{{ url_for(entity.lower() + '_routes.create_' + entity.lower()) }}">{{ gettext('Create') }} {{ entity }}</a></li>{% endfor %}
                    {% endif %}
                {% else %}
                    <li><a href="{{ url_for('routes.signup') }}">{{ gettext('Sign up') }}</a></li>
                    <li><a href="{{ url_for('routes.login') }}">{{ gettext('Log in') }}</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class="flashes">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </main>
</body>
</html>

qlerner/templates/choose_lesson.html
{% extends "base.html" %}

{% block content %}
  <h1>Choose a Lesson</h1>
  <div class="list-group">
    {% for lesson in lessons %}
      <a href="{{ url_for('routes.solve_lesson', lesson_id=lesson.id) }}" class="list-group-item">{{ lesson.title }}</a>
    {% endfor %}
  </div>
{% endblock %}

qlerner/templates/create_template.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h2>Create {{ entity_name }}</h2>
        <form method="POST" id="main-form" action="{{ url_for(entity_name.lower() + '_routes.create_' + entity_name.lower()) }}">
          {% for column in columns %}{% if column not in ['id', 'exercise_ids'] %}<label for="{{ column }}">{% for c in column.split('_') %}{{ c[0].upper() }}{{ c[1:].lower()}} {% endfor %}:</label>
          <input type="text" id="{{ column }}" name="{{ column }}" {{ 'required' if column in required }}><br>{% endif %}{% endfor %}
          <label for="tags">Tags :</label>
          <input type="hidden" name="exercises" id="exercises">
          <input type="text" id="tags" name="tags"><br>
          {% if entity_name == 'Lesson' %}
            {% set main_route = url_for('lesson_routes.create_lesson') %}{% include 'search_tags_subwindow.html' %}
            <button onclick="openPopup()" class="btn btn-outline-secondary">Add exercises</button>
          {% endif %}
          <input type="submit" class="btn btn-primary" value="Create {{ entity_name }}">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

qlerner/templates/dictionary.html
{% extends "base.html" %}

{% block content %}
	<h1>Words List</h1>
	<table>
	<thead>
		<tr>
		<th>English Meaning</th>
		<th>English Translation</th>
		<th>Quenya</th>
		<th>Quenya Transcription</th>
		</tr>
	</thead>
	<tbody>
		{% for word in words %}
		<tr>
		<td>{{ word.english_meaning }}</td>
		<td>{{ word.english_translation }}</td>
		<td>{{ word.quenya_tengwar|tw }}</td>
		<td>{{ word.quenya_transcription }}</td>
		</tr>
		{% endfor %}
	</tbody>
	</table>
{% endblock %}

qlerner/templates/edit_template.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <h2>Edit {{ entity_name }}</h2>
      <form method="POST">
        {% for column in columns %}{% if column not in ['id', 'exercise_ids'] %}<div class="form-group">
          <label for="{{ column }}">{% for c in column.split('_') %}{{ c[0].upper() }}{{ c[1:].lower()}} {% endfor %}:</label>
          <textarea class="form-control" id="{{ column }}" name="{{ column }}">{{ entity[column] if column not in ['password']}}</textarea>
        </div>{% endif %}{% endfor %}
        <input type="hidden" name="exercises" id="exercises">
        <div class="form-group">
          <label for="tags">Tags (comma-separated)</label>
          <input class="form-control" id="tags" name="tags" value="{{ entity['tags'] }}">
        </div>
        {% if entity_name == 'Lesson' %}
          {% set main_route = url_for('lesson_routes.edit_lesson', id = entity.id) %}{% include 'search_tags_subwindow.html' %}
          <button onclick="openPopup()" class="btn btn-outline-secondary">Add exercises</button>
        {% endif %}
        <button type="submit" class="btn btn-primary">Save</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

qlerner/templates/entity_template.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <h2>{{ entity_name }}</h2>
        <div class="row my-3">
          <div class="col-md-6">
            <form action="" method="GET">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search {{ entity_name|lower }}s..." name="search" value="{{ search }}">
                <div class="input-group-append">
                  <button href="{{ url_for(entity_name.lower() + '_routes.' + entity_name.lower() + 's') }}?search=search" class="btn btn-outline-secondary" type="submit">Search</button>
                </div>
              </div>
            </form>
          </div>
          <div class="col-md-6 text-right">
            <a href="{{ url_for(entity_name.lower() + '_routes.create_' + entity_name.lower()) }}" class="btn btn-primary">Add {{ entity_name }}</a>
            <button class="btn btn-secondary dropdown-toggle" type="button" id="sortDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Sort By {% if sort_by==None %}ID{% endif %}{% for c in sort_by.split('_') %}{{ c[0].upper() }}{{ c[1:].lower()}} {% endfor %}
            </button>
          </div>
        </div>
        <table class="table">
          <thead>
            <tr aria-labelledby="sortDropdown">
              <th scope="col"><a class="dropdown-item" href="{{ url_for(entity_name.lower() + '_routes.' + entity_name.lower() + 's') }}?sort_by=tags">Tags</a></th>
              {% for column in columns %}{% if column not in ['id', 'password'] %}<th scope="col"><a class="dropdown-item" href="{{ url_for(entity_name.lower() + '_routes.' + entity_name.lower() + 's') }}?sort_by={{ column }}">{% for c in column.split('_') %}{{ c[0].upper() }}{{ c[1:].lower()}} {% endfor %}</a></th>{% endif %}{% endfor %}
            </tr>
          </thead>
          <tbody>
            {% for entity in entities %}
            <tr>
              <th scope="row">{% if entity.tags==None %}—{% else %}{{ entity.tags }}{% endif %}</th>
              {% for column in entity[1:] %}<td>
                {{ column|tw if not (loop.last or (entity_name == 'User' and loop.index == 4)) }}
              </td>{% endfor%}
              <td>
                <div class="btn-group" role="group">
                    <a href="{{ url_for( entity_name.lower() + '_routes.edit_' + entity_name.lower(),  id=entity[0]) }}" class="btn btn-primary btn-sm">Edit</a>
                    {% if entity_name != 'User' %}<a href="{{ url_for( entity_name.lower() + '_routes.copy_' + entity_name.lower(),  id=entity[0]) }}" class="btn btn-info btn-sm">Copy</a>{% endif %}
                    <a href="{{ url_for( entity_name.lower() + '_routes.delete_' + entity_name.lower(), id=entity[0]) }}" class="btn btn-danger btn-sm">Delete</a>
                </div>                
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

qlerner/templates/index.html
{% extends "base.html" %}

{% block content %}
	<h1>Welcome to the Quenya Learning App!</h1>
	<p>This is a test of the Tengwar font.</p>
	<p>Here is a sentence in Tengwar: {{ '$<Annon edhellen, edro hi ammen!$>'|tw }}</p>
{% endblock %}

qlerner/templates/login.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h2>Login</h2>
        <form method="POST" action="{{ url_for('routes.login') }}">
          {{ form.csrf_token }}
          <div class="form-group">
            {{ form.login_data.label }} {{ form.login_data(class="form-control") }}
          </div>
          <div class="form-group">
            {{ form.password.label }} {{ form.password(class="form-control") }}
          </div>
          <button type="submit" class="btn btn-primary">Login</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

qlerner/templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1>Profile</h1>
    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Solved lessons: {{ solved_lessons }}</p>
{% endblock %}

qlerner/templates/search_tags_subwindow.html
{% block scripts %}
  <script>
    // Add event listener to button 1
    document.querySelector('#search').addEventListener('click', function(event) {
      event.preventDefault(); // prevent form from being submitted
      // Do something else, like redirect to the same URL with search query
      //window.location.href = window.location.pathname + '{{'?search=' + search if search }}{{ '?sort_by=' + sort_by if sort_by }}';
    });

    // Add event listener to button 2
    document.querySelector('#sort_by').addEventListener('click', function(event) {
      event.preventDefault(); // prevent form from being submitted
      // Do something else, like display an alert message
      console.log("Sort by pressed")
    });
    
    function openPopup() {
      // prevent the main form from submitting
      event.preventDefault();
      
      // open the popup window and load the included template
      var popup = window.open("", "popup", "width=600,height=400");
      popup.document.write(`<form id="popup-form">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search exercises..." name="search" value="{{ search }}">
            <div class="input-group-append">
                <button id='search' class="btn btn-outline-secondary">Search</button>
                <button id='sort_by' class="btn btn-secondary dropdown-toggle" type="button" id="sortDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Sort By {% if sort_by==None %}ID{% endif %}{% for c in sort_by.split('_') %}{{ c[0].upper() }}{{ c[1:].lower()}} {% endfor %}
                </button>
            </div>
        </div>
        <table>
            <thead>
                <tr>
                <th></th>
                {% for column in exercises[0]._asdict() %}
                <th><a id='{{ column }}' class="dropdown-item" href="{{ main_route }}{{ '?search=' + search if search }}?sort_by={{ column }}">{% for c in column.split('_') %}{{ c[0].upper() }}{{ c[1:].lower()}} {% endfor %}</a></th>
                {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for exercise in exercises %}{% set edict = exercise._asdict()%}
                <tr>
                <td><input type="checkbox" id={{ exercise.id }} name='exercises' value={{ exercise.id }}{% if entity and exercise.id.__str__() in entity.exercise_ids %} checked{% endif %}></td>
                {% for column in edict %}
                <td>{{ edict[column]|tw }}</td>
                {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>`);
      
      // add an event listener to the submit button in the popup window
      popup.document.querySelector("#popup-form").addEventListener("submit", function(event) {
        event.preventDefault();
    
        // get the checked options from the popup window
        var checkedExercises = Array.from(popup.document.querySelectorAll('input[name="exercises"]:checked')).map(function(checkbox) {
          return checkbox.value;
        });
    
        // close the popup window
        popup.close();
    
        // set the value of the hidden input in the main form to the checked options
        document.querySelector("#exercises").value = checkedExercises.join(",");
      });

      popup.document.querySelector("#popup-form").addEventListener("submit", popup.close)
    }
  </script>
{% endblock %}

qlerner/templates/signup.html
{% extends "base.html" %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h2>Sign Up</h2>
        <form method="POST" action="{{ url_for('routes.signup') }}">
          {{ form.csrf_token }}
          <div class="form-group">
            {{ form.username.label }} {{ form.username(class="form-control") }}
          </div>
          <div class="form-group">
            {{ form.email.label }} {{ form.email(class="form-control") }}
          </div>
          <div class="form-group">
            {{ form.password.label }} {{ form.password(class="form-control") }}
          </div>
          <div class="form-group">
            {{ form.confirm_password.label }} {{ form.confirm_password(class="form-control") }}
          </div>
          <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

qlerner/templates/solve_lesson.html
{% extends 'base.html' %}

{% block content %}
  <h3>{{ exercise.question|tw }}</h3>
  <form method="POST" action="{{ url_for('routes.solve_lesson', lesson_id=lesson.id, current_index=current_index) }}">
    {% if exercise.type == "choose one" %}
    {% for option in exercise.options %}
      <input type="radio" id="{{ option }}" name="answer" value="{{ option }}">
      <label for="{{ option }}">{{ option|tw }}</label><br>
    {% endfor %}
    {% elif exercise.type == "write" %}
      <input type="text" id="answer" name="answer">
    {% elif exercise.type == "audio" %}
        <audio controls>
          <source src="{{ exercise.audio_url }}" type="audio/mpeg">
          Your browser does not support the audio element.
        </audio>
        <input type="text" id="answer" name="answer">
    {% endif %}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

qlerner/templates/words.html
{% extends "base.html" %}

{% block content %}
	<h1>Words List</h1>
	<table>
	<thead>
		<tr>
		<th>English Meaning</th>
		<th>English Translation</th>
		<th>Quenya</th>
		<th>Quenya Transcription</th>
		</tr>
	</thead>
	<tbody>
		{% for word in words %}
		<tr>
		<td>{{ word.english_meaning }}</td>
		<td>{{ word.english_translation }}</td>
		<td>{{ word.quenya_tengwar|tw }}</td>
		<td>{{ word.quenya_transcription }}</td>
		</tr>
		{% endfor %}
	</tbody>
	</table>
{% endblock %}